var mongoose = require('mongoose');

var CustomerSchema = new mongoose.Schema({
	name: String,
	date: String,
	address: String,
	city: String,
	state: String,
	zip: String,
	phone: String,
	cell: String,
	email: String,
	rh: String,
	lh: String,
	conv: String,
	ft: String,
	ball: String,
	wgt: String,
	pin: String,
	layout: String,
	surface: String,
	bhPosition: String,
	size: String,
	depth: String,
	paph: String,
	papv: String,
	clt: String,
	thumb: String,
	fingers: String,
	price: String,
	completedBy: String,
	
	frac1: String,
	frac2: String,
	frac3: String,
	frac4: String,
	frac5: String,
	frac6: String,
	frac7: String,
	frac8: String,
	frac9: String,
	dec1: String,
	dec2: String,
	text1: String,
	text2: String,
	text3: String,
	cut1: String,
	fspan1: String,
	cut2: String,
	fspan2: String,
	radio1: String,
	radio2: String,
	radio3: String,
	radio4: String,
	radio5: String,
	radio6: String,
	
	ball1: String,
	weight1: String,
	pin1: String,
	layout1: String,
	bhpos1: String,
	bhsize1: String,
	bhdepth1: String,
	surface1: String,
	
	ball2: String,
	weight2: String,
	pin2: String,
	layout2: String,
	bhpos2: String,
	bhsize2: String,
	bhdepth2: String,
	surface2: String,
	
	ball3: String,
	weight3: String,
	pin3: String,
	layout3: String,
	bhpos3: String,
	bhsize3: String,
	bhdepth3: String,
	surface3: String,
	
	ball4: String,
	weight4: String,
	pin4: String,
	layout4: String,
	bhpos4: String,
	bhsize4: String,
	bhdepth4: String,
	surface4: String,
	
	ball5: String,
	weight5: String,
	pin5: String,
	layout5: String,
	bhpos5: String,
	bhsize5: String,
	bhdepth5: String,
	surface5: String,
	
	ball6: String,
	weight6: String,
	pin6: String,
	layout6: String,
	bhpos6: String,
	bhsize6: String,
	bhdepth6: String,
	surface6: String,
	
	ball7: String,
	weight7: String,
	pin7: String,
	layout7: String,
	bhpos7: String,
	bhsize7: String,
	bhdepth7: String,
	surface7: String,
	
	ball8: String,
	weight8: String,
	pin8: String,
	layout8: String,
	bhpos8: String,
	bhsize8: String,
	bhdepth8: String,
	surface8: String,
	
	ball9: String,
	weight9: String,
	pin9: String,
	layout9: String,
	bhpos9: String,
	bhsize9: String,
	bhdepth9: String,
	surface9: String,
	
	ball10: String,
	weight10: String,
	pin10: String,
	layout10: String,
	bhpos10: String,
	bhsize10: String,
	bhdepth10: String,
	surface10: String,
	
	notes: String,
	
	
	
});

mongoose.model('Customer', CustomerSchema);